---
# tasks file for router
- name: Install systemd-networkd packages
  package:
    name: systemd-networkd
    state: present
  when:
    - ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Remove resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: Link resolv.conf from systemd-networkd
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    state: link
    force: yes

- name: Create /etc/systemd/network file
  file:
    path: /etc/systemd/network
    owner: root
    group: root
    mode:  0755
    setype: etc_t
    state: directory

- name: Deploy WAN interface config
  template:
    src: router_wan_interface.j2
    dest: /etc/systemd/network/{{ router_wan_int_name }}.network
    owner: root
    group: root
    mode: 0644
    setype: etc_t
#  notify: restart systemd-networkd

- name: Deploy LAN interface config
  template:
    src: router_lan_interface.j2
    dest: /etc/systemd/network/{{ router_lan_int_name }}.network
    owner: root
    group: root
    mode: 0644
    setype: etc_t
#  notify: restart systemd-networkd

- name: Stop and disable NetworkManager.service
  systemd: state=stopped enabled=no name=NetworkManager
  when:
    - router_networkmanager_disable == true

- name: Stop and disable network.service
  systemd: state=stopped enabled=no name=network
  when:
    - router_networkservice_disable == true

- name: Start and enable systemd-networkd
  systemd: state=started enabled=yes name=systemd-networkd

- name: Start and enable systemd-resolved
  systemd: state=started enabled=yes name=systemd-resolved
